cluster.name: ${CLUSTER_NAME}

node.name: ${NODE_NAME}
node.ingest: ${NODE_INGEST_BOOL}
node.data: ${NODE_DATA_BOOL}
node.master: ${NODE_MASTER_BOOL}

path.data: ${PATH_DATA}
path.logs: ${PATH_LOGS}
path.repo: ${PATH_REPO}

network.host: ${NETWORK_HOST}
http.host: ${HTTP_HOST}
# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0

discovery.zen.minimum_master_nodes: ${DISCOVERY_MASTER_NODES}
discovery.zen.ping.unicast.hosts: ["0.0.0.0","127.0.0.1"]
